spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.jakarta.persistence.validation.mode=none

#linkedin.access.token=AQU9yL2B_0AI4egLCDk6W-ZGLEVb80m94DZQ0_aI6BBKdmrdDc-o8RVPgaIBXn7ESLxim_zJ0nhez-8alTs3C4ZunA8cjWERxg_bNlrm3ctjRytKygVmIr0UWJfu-OFG-vQoJIiuRUTD3U3rpR9ZrK4e0hHnwhhFo504W3h2eYM9kPelFseEMFhyU6KQhjw7y8SSETW446vbsgvp00_8PryBRTbeKw46ynWekEHkgQAht6QlmmWup_sqUvHuBUyZpaoYkQJUu-Xs7tGyMcBiUStbMESCtXJrvjARJ7UNuppBrE9VHgnHtsGxlrh3vXuVGaJzegn-p4ldSUWetuzjhuBIOGBvQg

#linkedin.access.token=AQVcHibQnNvCqRbpQN7xUuVH6posZOQziQzt6toIVvT6R_UzmzMztaN2N1uEE9sQdlwkKNJmr69JLKUiU0iW_Ntsm3ymaTTYc7DwEBCNBFLENN4cnvCdjoxVMzEHD0bh-BXD8y4LlSi895jAk2D50CXl5SZdPAqMbSthK4iLG60XLgeXZb9rgS0EFAygLYw8kR-8CXCzL3xTMdupxINtidXlPgno6hSgeDGuMMbeqb7fUVgf55Vg4cgV_p5NtyDt-_e96Qq48wFRi7wFK-gq9YH7iRMuyjU0EV5PTRKdxCJQcgdI8slfQ2mOSapsUNtYkbtgr2tIDvyQAdn0oNXmdms6E5YJ4A

linkedin.access.token=AQVidA6HuGzLCxnj9_Ucbn12gYXQH50wT-9Al-nc4mFktnBBYrVJtomGv8Erkuu8TlUW6mrZe8T-enniRBcaUN2jru-8dxhHBr_7jfg6wb9CjWQj8QTHtEHU-Ipibh7YOuJQFhoDtF9DvNUZB3rGxPFsJp6q0doXWO-k7Plr9j6Clud8tGYqDPdjjKDT-wZm2cGdLZVVEsPmsiGKZDLvgwcrJ-QbWO0moECfsBsZcThW4GET43tISoip0pFZEaqJ5DWpyFEn08FuMIz-f6s8uOf0gZre4onKM04TSTJ4N4EsQvwllbKG-UwGDrbWhTKIIWgcwCEXthd8bLnCf-Af3krdKRYtbg

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB